import { Geist, Poppins } from "next/font/google";
import "./globals.css";
import Link from "next/link";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ['400', '700'],
  subsets: ["latin"]
})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`p-6 ${poppins.variable} antialiased`}
      >
        <ul className="flex gap-5">
          <li><Link href='/'>Home</Link></li>
          <li><Link href='/about' >About</Link></li>
          <li><Link href='/blogs' >Blogs</Link></li>
          <li><Link href='/post' >Posts</Link></li>
        </ul>
        <hr />

        {children}
      </body>
    </html>
  );
}
